
### **.gitlab-ci.yml**
```yaml
stages:
  - validate
  - plan
  - apply

variables:
  TF_ROOT: "."
  TF_WORKSPACE: "dev"

before_script:
  - terraform --version
  - terraform init -backend-config="environment/lab/backend.hcl"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE
    - terraform plan -var-file="modules/irsaapps3landing-roles/dev.tfvars" -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform workspace select $TF_WORKSPACE
    - terraform apply -auto-approve tfplan
  when: manual
