AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create IAM role app-AST-S3-LANDING=fGLBAZADEDPInfra@I+000 based on app-AST-S3-ADMIN=fGLBAZADEDPInfra@I+000'

Parameters:
  EKSClusterName:
    Type: String
    Default: 'eks-astro-dev'
    Description: 'Name of the EKS cluster for OIDC provider'
  
  AWSAccountId:
    Type: String
    Default: '124930443440'
    Description: 'AWS Account ID'
  
  EKSRegion:
    Type: String
    Default: 'eu-west-1'
    Description: 'AWS Region where EKS cluster is deployed'
  
  AstronomerNamespace:
    Type: String
    Default: 'astronomer'
    Description: 'Kubernetes namespace for astronomer service accounts'

  EKSOIDCProviderId:
    Type: String
    Description: 'OIDC Provider ID from EKS cluster (obtain from cluster.identity.oidc.issuer)'
    Default: 'CD2E2C37BED785E8F4FF87A4A98FAD3'

Resources:
  # IAM Role with OIDC trust policy
  ASTLandingIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'app-AST-S3-LANDING=fGLBAZADEDPInfra@I+000'
      Description: 'IAM role for Astronomer S3 Landing operations with EKS OIDC integration'
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Allow assumption by users and federation roles
          - Effect: Allow
            Principal:
              AWS: 
                - !Sub 'arn:aws:iam::${AWSAccountId}:user/FederationUser'
                - !Sub 'arn:aws:iam::778914484860:role/federation-role'
                - !Sub 'arn:aws:iam::524505257659:role/federation-role'
            Action: 'sts:AssumeRole'
          
          # OIDC provider for EKS cluster
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWSAccountId}:oidc-provider/oidc.eks.${EKSRegion}.amazonaws.com/id/${EKSOIDCProviderId}'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                "oidc.eks.${EKSRegion}.amazonaws.com/id/${EKSOIDCProviderId}:sub": !Sub "system:serviceaccount:${AstronomerNamespace}:*"
          
          # Service principal for other AWS services
          - Effect: Allow
            Principal:
              Service:
                - lakeformation.amazonaws.com
                - glue.amazonaws.com
                - rds.amazonaws.com
                - elasticmapreduce.amazonaws.com
            Action: 'sts:AssumeRole'
      
      # Attach managed policies
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonRDSDataFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonRDSFullAccess'
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/SecretsManagerReadWrite'
        - 'arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
      
      Tags:
        - Key: 'CORE-ROLE-OWNER'
          Value: 'Application'
        - Key: 'CORE-ROLE-PRIVILEGE'
          Value: 'High'
        - Key: 'portfolio-owner'
          Value: 'application'
        - Key: 'Purpose'
          Value: 'Astronomer S3 Landing Operations'
        - Key: 'Environment'
          Value: 'Development'

  # Inline Policy: ChangeSecretsPolicy
  ChangeSecretsPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'ChangeSecretsPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'secretsmanager:CreateSecret'
              - 'secretsmanager:UpdateSecret'
              - 'secretsmanager:DeleteSecret'
              - 'secretsmanager:RestoreSecret'
              - 'secretsmanager:RotateSecret'
              - 'secretsmanager:UpdateSecretVersionStage'
              - 'secretsmanager:EnableKeyRotation'
              - 'secretsmanager:DisableKeyRotation'
              - 'secretsmanager:TagResource'
              - 'secretsmanager:UntagResource'
              - 'secretsmanager:PutResourcePolicy'
              - 'secretsmanager:DeleteResourcePolicy'
            Resource:
              - !Sub 'arn:aws:secretsmanager:eu-west-1:${AWSAccountId}:secret:/app/astronomer/dev/spoke/*'
              - !Sub 'arn:aws:secretsmanager:eu-west-1:${AWSAccountId}:secret:/app/astronomer/dev/hub/*'
              - !Sub 'arn:aws:secretsmanager:eu-west-1:${AWSAccountId}:secret:/app/astronomer/dev/*'
              - !Sub 'arn:aws:secretsmanager:eu-west-1:${AWSAccountId}:secret:/app/astronomer/int/spoke/*'
              - !Sub 'arn:aws:secretsmanager:eu-west-1:${AWSAccountId}:secret:/app/astronomer/int/hub/*'
              - !Sub 'arn:aws:secretsmanager:eu-west-1:${AWSAccountId}:secret:/app/astronomer/int/*'
          - Effect: Allow
            Action: '*'
            Resource: '*'
      Roles:
        - !Ref ASTLandingIAMRole

  # Inline Policy: DynamoDbTfStateEditPolicy
  DynamoDbTfStateEditPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'DynamoDbTfStateEditPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:ConditionCheckItem'
              - 'dynamodb:CreateBackup'
              - 'dynamodb:CreateTable'
              - 'dynamodb:DeleteBackup'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:DeleteTable'
              - 'dynamodb:PutItem'
              - 'dynamodb:RestoreTableFromBackup'
              - 'dynamodb:RestoreTableToPointInTime'
              - 'dynamodb:TagResource'
              - 'dynamodb:UntagResource'
              - 'dynamodb:UpdateContinuousBackups'
              - 'dynamodb:UpdateContributorInsights'
              - 'dynamodb:UpdateGlobalTable'
              - 'dynamodb:UpdateGlobalTableSettings'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:UpdateTable'
              - 'dynamodb:UpdateTableReplicaAutoScaling'
              - 'dynamodb:UpdateTimeToLive'
            Resource:
              - !Sub 'arn:aws:dynamodb:eu-west-1:${AWSAccountId}:table/astronomer-barclays-eu-tfstate-dev'
              - !Sub 'arn:aws:dynamodb:eu-west-1:${AWSAccountId}:table/astronomer-barclays-eu-tfstate-dev/*'
              - !Sub 'arn:aws:dynamodb:eu-west-1:${AWSAccountId}:table/astronomer-barclays-eu-tfstate-int'
              - !Sub 'arn:aws:dynamodb:eu-west-1:${AWSAccountId}:table/astronomer-barclays-eu-tfstate-int/*'
          - Effect: Allow
            Action: '*'
            Resource: '*'
      Roles:
        - !Ref ASTLandingIAMRole

  # Inline Policy: KMSAccessPolicy
  KMSAccessPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'KMSAccessPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:CreateGrant'
              - 'kms:RevokeGrant'
              - 'kms:PutKeyPolicy'
              - 'kms:Put*'
              - 'kms:List*'
              - 'kms:Describe*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
              - 'kms:TagResource'
              - 'kms:UntagResource'
              - 'kms:Create*'
              - 'kms:Enable*'
              - 'kms:CreateAlias'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
            Resource: '*'
          - Effect: Allow
            Action: '*'
            Resource: '*'
      Roles:
        - !Ref ASTLandingIAMRole

  # Inline Policy: S3BucketTfStateEditPolicy
  S3BucketTfStateEditPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'S3BucketTfStateEditPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:PutBucketPolicy'
              - 's3:DeleteBucketPolicy'
              - 's3:PutBucketAcl'
              - 's3:PutBucketCors'
              - 's3:DeleteBucketCors'
              - 's3:PutBucketLogging'
              - 's3:PutBucketTagging'
              - 's3:DeleteBucketTagging'
              - 's3:PutBucketVersioning'
              - 's3:PutBucketWebsite'
              - 's3:DeleteBucketWebsite'
              - 's3:PutBucketNotification'
              - 's3:PutBucketLifecycle'
              - 's3:DeleteBucketLifecycle'
              - 's3:PutBucketReplication'
              - 's3:DeleteBucketReplication'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:AbortMultipartUpload'
              - 's3:PutObjectAcl'
              - 's3:DeleteObjectVersion'
              - 's3:PutObjectVersionAcl'
              - 's3:RestoreObject'
              - 's3:PutObjectTagging'
              - 's3:DeleteObjectTagging'
              - 's3:PutObjectVersionTagging'
            Resource:
              - !Sub 'arn:aws:s3:::${AWSAccountId}-eu-west-1-tf-state-bucket-astronomer-dev'
              - !Sub 'arn:aws:s3:::${AWSAccountId}-eu-west-1-tf-state-bucket-astronomer-dev/*'
              - !Sub 'arn:aws:s3:::${AWSAccountId}-eu-west-1-tf-state-bucket-astronomer-int'
              - !Sub 'arn:aws:s3:::${AWSAccountId}-eu-west-1-tf-state-bucket-astronomer-int/*'
          - Effect: Allow
            Action: '*'
            Resource: '*'
      Roles:
        - !Ref ASTLandingIAMRole

Outputs:
  IAMRoleArn:
    Description: 'ARN of the created IAM role'
    Value: !GetAtt ASTLandingIAMRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-IAMRoleArn'
  
  IAMRoleName:
    Description: 'Name of the created IAM role'
    Value: !Ref ASTLandingIAMRole
    Export:
      Name: !Sub '${AWS::StackName}-IAMRoleName'
  
  OIDCProviderArn:
    Description: 'OIDC Provider ARN for EKS integration'
    Value: !Sub 'arn:aws:iam::${AWSAccountId}:oidc-provider/oidc.eks.${EKSRegion}.amazonaws.com/id/${EKSOIDCProviderId}'
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderArn'
