AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS Service Catalog Product - CrossAccountAssumeRole
  Configures cross-account IAM roles between an EKS cluster (Account A)
  and target account (Account B) for controlled S3 access using IRSA or Pod Identity.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Account Configuration'
        Parameters:
          - SourceAccountId
          - TargetAccountId
          - AWSRegion
      - Label:
          default: 'EKS Cluster Configuration'
        Parameters:
          - EKSClusterName
          - KubernetesNamespace
          - ServiceAccountName
      - Label:
          default: 'IAM Role Configuration'
        Parameters:
          - RoleAName
          - RoleBName
          - PolicyAName
          - PolicyBName
      - Label:
          default: 'S3 Access Configuration'
        Parameters:
